# Use root/example as user/password credentials
version: '3.1'

services:
    firebird:
        container_name: firebird
        image: jacobalberty/firebird:2.5-ss       
        restart: always
        environment: 
            ISC_PASSWORD: masterkey  
        ports: 
            - 3050:3050
        volumes: 
            - ./data:/firebird/data